# .github/workflows/debug-repository-creation.yml
name: Debug Repository Creation

on:
  repository_dispatch:
    types: [created]

jobs:
  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Information
        run: |
          echo "============ Event Information ============"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Organization: ${{ github.repository_owner }}"
          echo "Action: ${{ github.event.action }}"
          echo "Sender: ${{ github.event.sender.login }}"
          echo "=========================================="