# .github/workflows/debug-repository-creation.yml
name: Debug Repository Creation

on:
  create
  workflow_dispatch

jobs:
  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "Full Context:"
          echo "$GITHUB_CONTEXT"
          echo "Basic Info:"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Organization: ${{ github.repository_owner }}"