# .github/workflows/debug-repository-creation.yml
name: Debug Repository Creation

on:
  create:
  workflow_dispatch:

jobs:
  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Debug Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Organization: ${{ github.repository_owner }}"
          echo "Event Type: ${{ github.event.ref_type }}"