# .github/workflows/debug-repository-creation.yml
name: Debug Repository Creation

on:
  create: {}
  workflow_dispatch: {}

jobs:
  debug-info:
    runs-on: ubuntu-latest
    # createイベントの時だけ実行条件を確認
    if: github.event_name == 'create'
    steps:
      - name: Print Event Information
        run: |
          echo "============ Event Information ============"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Type: ${{ github.event.ref_type }}"
          echo "Repository: ${{ github.repository }}"
          echo "Organization: ${{ github.repository_owner }}"
          echo "=========================================="